contigua100000:
	gcc -c ./filaContigua/fila_contigua.c -o ./filaContigua/fila_contigua.o
	gcc ./filaContigua/main_100000.c ./filaContigua/fila_contigua.o -o ./filaContigua/main_filaContigua
	./filaContigua/main_filaContigua

	valgrind --leak-check=full ./filaContigua/main_filaContigua

contigua50000:
	gcc -c ./filaContigua/fila_contigua.c -o ./filaContigua/fila_contigua.o
	gcc ./filaContigua/main_50000.c ./filaContigua/fila_contigua.o -o ./filaContigua/main_filaContigua
	./filaContigua/main_filaContigua

	valgrind --leak-check=full ./filaContigua/main_filaContigua

contigua1000:
	gcc -c ./filaContigua/fila_contigua.c -o ./filaContigua/fila_contigua.o
	gcc ./filaContigua/main_1000.c ./filaContigua/fila_contigua.o -o ./filaContigua/main_filaContigua
	./filaContigua/main_filaContigua

	valgrind --leak-check=full ./filaContigua/main_filaContigua

#--------------------------------------------------------------------------------

encadeada100000:
	gcc -c ./filaEncadeada/fila_encadeada.c -o ./filaEncadeada/fila_encadeada.o
	gcc ./filaEncadeada/main_100000.c ./filaEncadeada/fila_encadeada.o -o ./filaEncadeada/main_filaEncadeada
	./filaEncadeada/main_filaEncadeada

	valgrind --leak-check=full ./filaEncadeada/main_filaEncadeada

encadeada50000:
	gcc -c ./filaEncadeada/fila_encadeada.c -o ./filaEncadeada/fila_encadeada.o
	gcc ./filaEncadeada/main_50000.c ./filaEncadeada/fila_encadeada.o -o ./filaEncadeada/main_filaEncadeada
	./filaEncadeada/main_filaEncadeada

	valgrind --leak-check=full ./filaEncadeada/main_filaEncadeada

encadeada1000:
	gcc -c ./filaEncadeada/fila_encadeada.c -o ./filaEncadeada/fila_encadeada.o
	gcc ./filaEncadeada/main_1000.c ./filaEncadeada/fila_encadeada.o -o ./filaEncadeada/main_filaEncadeada
	./filaEncadeada/main_filaEncadeada

	valgrind --leak-check=full ./filaEncadeada/main_filaEncadeada
	
