contigua:
	gcc -c pilha_contigua.c -o pilha_contigua.o
	gcc main.c pilha_contigua.o -o main_pilhaContigua
	./main_pilhaContigua

encadeada:
	gcc -c pilha_encadeada.c -o pilha_encadeada.o
	gcc main.c pilha_encadeada.o -o main_pilhaEncadeada
	./main_pilhaEncadeada

encadeada_01:
	gcc -c pilha_encadeada.c -o pilha_encadeada.o
	gcc atividade01_B.c pilha_encadeada.o -o atividade01_B
	./atividade01_B	

clean:
	rm *.o
	rm main_pilhaContigua
	rm main_pilhaEncadeada